import os
import re
from fastapi import APIRouter, UploadFile, File, HTTPException, status
from groq import Groq
from dotenv import load_dotenv

# --- Load environment ---
load_dotenv()

router = APIRouter()

# --- Config ---
GROQ_API_KEY = os.getenv("GROQ_API_KEY")
if not GROQ_API_KEY:
    raise RuntimeError("❌ GROQ_API_KEY missing in .env")

GROQ_MODEL = os.getenv("GROQ_MODEL", "llama-3.3-70b-versatile")
MAX_UPLOAD_BYTES = int(os.getenv("MAX_UPLOAD_BYTES", 200 * 1024))  # 200KB

# --- Initialize client ---
client = Groq(api_key=GROQ_API_KEY)


def _redact_secrets(text: str) -> str:
    """Redact possible secrets before sending to Groq."""
    text = re.sub(r"sk-[A-Za-z0-9\-_]{16,}", "[REDACTED_KEY]", text)
    text = re.sub(r"[A-Fa-f0-9]{40,}", "[REDACTED_HEX]", text)
    text = re.sub(r"AKIA[0-9A-Z]{16}", "[REDACTED_AWS_KEY]", text)
    return text


@router.post("/upload")
async def upload_code_file(file: UploadFile = File(...)):
    """
    Accepts a file upload, sends its contents to Groq for a detailed code review,
    and returns AI feedback.
    """
    try:
        contents = await file.read()
        if not contents:
            raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail="Uploaded file is empty")

        if len(contents) > MAX_UPLOAD_BYTES:
            raise HTTPException(
                status_code=status.HTTP_413_REQUEST_ENTITY_TOO_LARGE,
                detail=f"File too large. Max allowed is {MAX_UPLOAD_BYTES} bytes",
            )

        try:
            code_text = contents.decode("utf-8")
        except Exception:
            code_text = contents.decode("latin-1", errors="ignore")

        safe_code = _redact_secrets(code_text)

        prompt = f"""
You are an AI Code Review Assistant.

Your job is to produce a **clean, beautiful, structured, developer-friendly report**.

### Follow this exact format:

# 🚀 AI Code Review Report

---

## 🧩 1. Summary  
Give a **2–4 line explanation** of what the code does.  
Keep it crisp and readable.

---

## ⚠️ 2. Issues & Potential Bugs  
List clear issues with:
- ❗ Short title  
- 📍 Line number (if possible)  
- 📝 Explanation  

Example:

**❗ Unused Import (Line 12)**  
This import is never used, which may indicate leftover code.

Provide 3–8 such findings.

---

## 💡 3. Suggestions for Improvement  
Provide **helpful, practical suggestions**, grouped like:

### 🔐 Security  
(Any concerns)

### ⚡ Performance  
(Any slow or inefficient operations)

### 🎨 Code Style / Cleanliness  
Spacing, naming, formatting, unused code, structure, etc.

### 🧠 Architecture / Best Practices  
Modularity, functions, separation of concerns, etc.

Make it professional but simple.

---

## 🎯 4. Hints (Optional but Useful)  
Add 2–3 small hints that could help the developer learn something.  
This section is meant as “extra learning”, not criticism.

Example:  
💡 *“You can use `np.where()` instead of loops to simplify conditional array operations.”*

---

## ⭐ 5. Code Quality Score  
Give a **score out of 10** with a one-line explanation.

Format like:

**⭐ Score: 7/10 — Well-written example code but lacks structure and consistency.**

---

### The Code to Review:

Code:
{safe_code}
"""

        print(f"🚀 Sending code to Groq model: {GROQ_MODEL}")

        completion = client.chat.completions.create(
            model=GROQ_MODEL,
            messages=[{"role": "user", "content": prompt}],
            temperature=0.4,
            max_tokens=1500,
        )

        review_output = completion.choices[0].message.content.strip()

        if not review_output:
            review_output = "No feedback generated by the AI model."

        print("✅ Review generated successfully.")
        return {"feedback": review_output}

    except HTTPException:
        raise
    except Exception as e:
        print(f"❌ Error: {e}")
        raise HTTPException(status_code=500, detail=f"AI provider error: {e}")
